print('Hello, world')
print('xique-xique bahia')
print('fulanodetown')
print('barpaquera')
print('sucesso')
print('eu sou linda')
print('santos')
print('ray')
print('eu amo meu namorado')
print('jesus')